# Generated by Django 5.2.1 on 2025-05-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientele', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrylogo',
            name='image',
            field=models.ImageField(default='alt text', upload_to='customer_logo/country_wise/'),
        ),
        migrations.AlterField(
            model_name='sectorlogo',
            name='alt_text',
            field=models.CharField(default='alt text', max_length=255),
        ),
    ]
