# Generated by Django 5.2.1 on 2025-05-13 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('story_heading', models.CharField(max_length=255)),
                ('story_paragraph', models.TextField()),
                ('founder_image', models.ImageField(upload_to='founder/')),
                ('para1', models.TextField()),
                ('para2', models.TextField()),
                ('mission_heading', models.CharField(max_length=255)),
                ('mission_paragraph', models.TextField()),
                ('mission_image', models.ImageField(upload_to='about/mission/')),
                ('vision_heading', models.CharField(max_length=255)),
                ('vision_paragraph', models.TextField()),
                ('vision_image', models.ImageField(upload_to='about/vision/')),
                ('values_heading', models.CharField(max_length=255)),
                ('values_image', models.ImageField(upload_to='about/values/')),
                ('values_points', models.JSONField(default=list)),
                ('faq_heading', models.CharField(max_length=255)),
                ('faq_paragraph', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='core.aboutpagecontent')),
            ],
        ),
    ]
