# Generated by Django 5.2.1 on 2025-05-14 07:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='home',
        ),
        migrations.AddField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='in_between_image',
            field=models.ImageField(blank=True, upload_to='blogs/in_between/'),
        ),
        migrations.AddField(
            model_name='blog',
            name='long_description',
            field=models.TextField(default='abcd'),
        ),
        migrations.AddField(
            model_name='blog',
            name='quote',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='short_description',
            field=models.TextField(default='abcd'),
        ),
        migrations.AddField(
            model_name='blog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('full-time', 'Full Time'), ('part-time', 'Part Time'), ('internship', 'Internship'), ('contract', 'Contract')], max_length=20),
        ),
    ]
