# Generated by Django 5.2.1 on 2025-05-15 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_blog_long_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievement',
            old_name='number',
            new_name='count',
        ),
        migrations.AddField(
            model_name='achievement',
            name='delay',
            field=models.CharField(default='.4s'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='suffix',
            field=models.CharField(default=''),
        ),
    ]
