# Generated by Django 5.2.1 on 2025-05-15 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_number_achievement_count_achievement_delay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpagecontent',
            name='achievements',
            field=models.JSONField(default=list),
        ),
    ]
