# Generated by Django 5.2.1 on 2025-05-15 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_aboutpagecontent_achievements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpagecontent',
            name='achievements',
        ),
        migrations.AddField(
            model_name='achievement',
            name='about',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='core.aboutpagecontent'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='home',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='core.homepagecontent'),
        ),
    ]
