# Generated by Django 5.2.1 on 2025-05-15 05:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_aboutpagecontent_achievements_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='services/')),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=100)),
                ('description1', models.TextField()),
                ('heading', models.CharField(max_length=255)),
                ('description2', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ValueAddedService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('para1', models.TextField()),
                ('para2', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='core.service')),
            ],
        ),
    ]
