# Generated by Django 5.2.1 on 2025-05-16 18:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_country_sector_sectorlogo_subcountry_countrylogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('excerpt', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='team/')),
                ('bio', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
