# Generated by Django 5.2.1 on 2025-05-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontent',
            name='achievements_heading',
            field=models.CharField(default='Achievements', max_length=200),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='locations_heading',
            field=models.CharField(default='Our Locations', max_length=200),
        ),
    ]
