# Generated by Django 5.2.1 on 2025-05-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_homepagecontent_achievements_heading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpagecontent',
            name='achievements_heading',
            field=models.CharField(default='Achievements', max_length=200),
        ),
    ]
