# Generated by Django 5.2.1 on 2025-05-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_aboutpagecontent_achievements_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpagecontent',
            name='team_heading',
            field=models.CharField(default='Our Team', max_length=200),
        ),
    ]
