# Generated by Django 5.2.1 on 2025-05-19 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_aboutpagecontent_team_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='prefix',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='icon',
            field=models.ImageField(upload_to='achievements/'),
        ),
    ]
