# Generated by Django 5.2.1 on 2025-05-19 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_achievement_icon_alter_achievement_prefix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliationitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='airpartneritem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='associationitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clienteleitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='is_achievements',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='is_affiliations',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='is_air_partners',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='is_associations',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='is_blogs',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='is_clientele',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='is_hero',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='is_journey',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='is_locations',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='is_sea_partners',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='is_services',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='location',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='seapartneritem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
