# Generated by Django 5.2.1 on 2025-05-19 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_affiliationitem_is_active_airpartneritem_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagecontent',
            name='achievements_heading',
            field=models.CharField(blank=True, default='Achievements', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='affiliations_heading',
            field=models.CharField(blank=True, default='Affiliations & Accreditation', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='air_partners_heading',
            field=models.CharField(blank=True, default='Air Carrier Partners', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='associations_heading',
            field=models.CharField(blank=True, default='Associations', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='clientele_heading',
            field=models.CharField(blank=True, default='Our Clientele', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='journey_heading',
            field=models.CharField(blank=True, default='Our Journey', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='locations_heading',
            field=models.CharField(blank=True, default='Our Locations', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='sea_partners_heading',
            field=models.CharField(blank=True, default='Sea Carrier Partners', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='services_heading',
            field=models.CharField(blank=True, default='Our Services', max_length=200, null=True),
        ),
    ]
