# Generated by Django 5.2.1 on 2025-05-19 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_homepagecontent_achievements_heading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontent',
            name='selected_services',
            field=models.ManyToManyField(blank=True, help_text='Select up to 6 services to feature on the homepage.', to='core.service'),
        ),
    ]
