# Generated by Django 5.2.1 on 2025-05-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_homepagecontent_selected_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcountry',
            name='country',
        ),
        migrations.RemoveField(
            model_name='countrylogo',
            name='subcountry',
        ),
        migrations.RemoveField(
            model_name='sectorlogo',
            name='sector',
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='is_achievements',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='is_faq',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='is_mission',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='is_story',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='is_team',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='is_values',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='is_vision',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='achievement',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='servicebenefit',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='valueaddedservice',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='CountryLogo',
        ),
        migrations.DeleteModel(
            name='SubCountry',
        ),
        migrations.DeleteModel(
            name='Sector',
        ),
        migrations.DeleteModel(
            name='SectorLogo',
        ),
    ]
