# Generated by Django 5.2.1 on 2025-05-19 19:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_subcountry_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='aboutpagecontent',
            name='is_achievements',
        ),
        migrations.RemoveField(
            model_name='aboutpagecontent',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='aboutpagecontent',
            name='is_faq',
        ),
        migrations.RemoveField(
            model_name='aboutpagecontent',
            name='is_mission',
        ),
        migrations.RemoveField(
            model_name='aboutpagecontent',
            name='is_story',
        ),
        migrations.RemoveField(
            model_name='aboutpagecontent',
            name='is_team',
        ),
        migrations.RemoveField(
            model_name='aboutpagecontent',
            name='is_values',
        ),
        migrations.RemoveField(
            model_name='aboutpagecontent',
            name='is_vision',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='job',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='service',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='servicebenefit',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='valueaddedservice',
            name='is_active',
        ),
        migrations.CreateModel(
            name='SectorLogo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='customer_logo/sector_wise/')),
                ('alt_text', models.CharField(max_length=255)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logos', to='core.sector')),
            ],
        ),
        migrations.CreateModel(
            name='SubCountry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcountries', to='core.country')),
            ],
        ),
        migrations.CreateModel(
            name='CountryLogo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='customer_logo/country_wise/')),
                ('alt_text', models.CharField(max_length=255)),
                ('subcountry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logos', to='core.subcountry')),
            ],
        ),
    ]
