# Generated by Django 5.2.1 on 2025-05-19 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_country_sector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpagecontent',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
