# Generated by Django 5.2.1 on 2025-05-19 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_aboutpagecontent_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpagecontent',
            name='is_mission',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='is_values',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='is_vision',
            field=models.BooleanField(default=True),
        ),
    ]
