# Generated by Django 5.2.1 on 2025-05-19 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_aboutpagecontent_is_mission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpagecontent',
            name='is_achievements',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='is_faq',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='is_story',
            field=models.BooleanField(default=True),
        ),
    ]
