# Generated by Django 5.2.1 on 2025-05-20 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_aboutpagecontent_is_achievements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
