# Generated by Django 5.2.1 on 2025-05-20 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_faq_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpagecontent',
            name='is_achievements',
        ),
    ]
