# Generated by Django 5.2.1 on 2025-05-20 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_aboutpagecontent_is_achievements'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpagecontent',
            name='is_achievements',
            field=models.BooleanField(default=True),
        ),
    ]
