# Generated by Django 5.2.1 on 2025-05-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_galleryevent_galleryphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('address_title', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('contact_title', models.CharField(max_length=255)),
                ('phone_label', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('phone_href', models.CharField(max_length=100)),
                ('email_label', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('email_href', models.CharField(max_length=100)),
                ('iframe', models.TextField()),
            ],
        ),
    ]
