# Generated by Django 5.2.1 on 2025-05-20 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_contactinfo_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactInfo',
        ),
    ]
