# Generated by Django 5.2.1 on 2025-05-20 17:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_delete_contactinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('address_title', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('contact_title', models.CharField(max_length=255)),
                ('phone_label', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('phone_href', models.CharField(max_length=100)),
                ('email_label', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('email_href', models.CharField(max_length=100)),
                ('iframe', models.TextField()),
            ],
        ),
    ]
