# Generated by Django 5.2.1 on 2025-05-21 07:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_contactquery'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('tag', models.JSONField(default=list)),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='news/')),
                ('short_description', models.TextField()),
                ('long_description', models.TextField()),
                ('quote', models.TextField(blank=True)),
                ('in_between_image', models.ImageField(blank=True, upload_to='News/in_between/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.RenameField(
            model_name='homepagecontent',
            old_name='is_blogs',
            new_name='is_news',
        ),
    ]
