# Generated by Django 5.2.1 on 2025-05-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_news_delete_blog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.CharField(default='', max_length=20),
        ),
    ]
