# Generated by Django 5.2.1 on 2025-05-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_news_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(default='Transport', max_length=20),
        ),
    ]
