# Generated by Django 5.2.1 on 2025-05-21 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_news_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='about',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='core.aboutpagecontent'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='home',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='core.homepagecontent'),
        ),
    ]
