# Generated by Django 5.2.1 on 2025-05-21 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_achievement_about_alter_achievement_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_industry', models.BooleanField(default=False)),
                ('is_gallery', models.BooleanField(default=False)),
                ('is_career', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='achievement',
            name='home',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='core.homepagecontent'),
        ),
    ]
