# Generated by Django 5.2.1 on 2025-05-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_pagespecification_alter_achievement_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustrySpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_industry', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='PageSpecification',
        ),
    ]
