# Generated by Django 5.2.1 on 2025-05-21 13:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_industryspecification_delete_pagespecification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industryspecification',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
