# Generated by Django 5.2.1 on 2025-05-22 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_industryspecification_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('para', 'Paragraph'), ('bullet', 'Bullet Points')], max_length=10)),
                ('content', models.TextField(blank=True, null=True)),
                ('list_items', models.JSONField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='industry_images/')),
                ('is_image_left', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
