# Generated by Django 5.2.1 on 2025-11-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagecontent',
            name='journey_video',
            field=models.FileField(blank=True, null=True, upload_to='videos/journey/JDM_Timeline.mp4'),
        ),
    ]
