# Generated by Django 5.2.1 on 2025-11-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_homepagecontent_journey_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagecontent',
            name='journey_video',
            field=models.FileField(blank=True, null=True, upload_to='videos/journey/'),
        ),
    ]
