# Generated by Django 5.2.1 on 2025-12-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_alter_homepagecontent_journey_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpagecontent',
            name='key_strengths_heading',
            field=models.CharField(default='Our Key Strengths', max_length=255),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='key_strengths_points',
            field=models.JSONField(default=list),
        ),
    ]
