# Generated by Django 5.2.1 on 2025-12-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_homeserviceorder_delete_serviceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpagecontent',
            name='story_points',
            field=models.JSONField(default=list),
        ),
    ]
