# Generated by Django 5.2.1 on 2025-12-14 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_aboutpagecontent_story_points'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='service',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
